# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  tags:
    include:
    - rc-*

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  artifactNugetName: 'KMA.Offboard.NLoptNET'
  versionSuffix: '$(Build.SourceBranchName)'

stages:
- stage: Build
  dependsOn: []
  jobs:
  - job: Build
    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'Running tests'
      inputs:
        command: 'test'
        projects: '$(solution)'
        arguments: '--configuration $(buildConfiguration)'
        publishTestResults: true

    - task: DotNetCoreCLI@2
      displayName: 'Creating nuget packages'
      condition: succeeded()
      inputs:
        command: 'custom'
        custom: 'pack'
        arguments: '--configuration $(buildConfiguration) -o $(build.artifactStagingDirectory)  --version-suffix $(versionSuffix)'

    - publish: '$(build.artifactStagingDirectory)'
      displayName: 'Publish Artifact: $(artifactNugetName)'
      artifact: '$(artifactNugetName)'

  - stage: PublishNuget
    dependsOn:
    - Build
    condition: succeeded()
    displayName: "Publish Nuget Packages"
    jobs:
    - job: PublishNuget
      steps:
      - download: current
        artifact: '$(ArtifactNugetName)'
        displayName: 'Download nuget packages'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'push'
          packagesToPush: '$(Agent.BuildDirectory)/$(ArtifactNugetName)/*.nupkg'
          nuGetFeedType: 'internal'
          publishVstsFeed: '368fd3b5-1cec-432d-937d-f006ee177508/28f11f8b-4d6c-4db4-808d-da3a2097c093'
