# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  artifactNugetName: 'KMA.Offboard.NLoptNET'

steps:
- template: pipeline_templates/generate_artifacts.yml
  parameters:
    buildPlatform: $(buildPlatform)
    buildConfiguration: $(buildConfiguration)
    solution: $(solution)
    artifactName: $(artifactNugetName)
